---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
    driver:
      network:
      - ["private_network", {ip: "192.168.33.34"}]
  - name: centos-7.2
    driver:
      network:
      - ["private_network", {ip: "192.168.33.33"}]

suites:
  - name: default
    run_list:
      - recipe[deluge-torrent::default]
    attributes:
